### ISSUE TITLE
How do i use telegram signals?

### ISSUE THREAD

**Issue by reliefs** [Trading-Bot/CryptoBot#167]
Hi, i have bought some signals from mininghamster how can i implement them? they are using telegram

**Comment by Herklos** [comment]
Hi ! 
If you ask us to explain how to use mininghamster services : I can't help you because it's not our project, here is CryptoBot.

If you ask us to explain how you can integrate the signals you bought into our bot : It is not currently implemented,  but you can make a feature request to describe your needs (https://github.com/Trading-Bot/CryptoBot/issues/new?template=feature_request.md).

**Comment by reliefs** [comment]
Thanks yes i'm looking for a way to integrate signals. Do you know any other bots there do this ?
